# Generated by Django 3.2.1 on 2021-06-04 11:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('user_id', models.TextField(db_column='아이디', primary_key=True, serialize=False)),
                ('age', models.IntegerField(choices=[(10, 10), (20, 20), (30, 30), (40, 40)], db_column='나이')),
                ('gender', models.CharField(choices=[('여', '남'), ('남', '여')], db_column='성별', max_length=5)),
                ('job', models.CharField(choices=[('학생', '학생'), ('프리랜서', '프리랜서'), ('무직', '무직'), ('직장인', '직장인')], db_column='직업', max_length=20)),
                ('room_name', models.CharField(db_column='방이름', max_length=50)),
                ('room_size', models.IntegerField(db_column='방크기')),
            ],
            options={
                'db_table': '사용자 정보',
            },
        ),
        migrations.CreateModel(
            name='Fixed_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitchen', models.PositiveIntegerField(db_column='주방', validators=[django.core.validators.MaxValueValidator(25)])),
                ('frige', models.PositiveIntegerField(db_column='냉장고', validators=[django.core.validators.MaxValueValidator(25)])),
                ('toilet', models.PositiveIntegerField(db_column='화장실', validators=[django.core.validators.MaxValueValidator(25)])),
                ('bed', models.PositiveIntegerField(db_column='침대', validators=[django.core.validators.MaxValueValidator(25)])),
                ('closet', models.PositiveIntegerField(db_column='옷장', validators=[django.core.validators.MaxValueValidator(25)])),
                ('washer', models.PositiveIntegerField(db_column='세탁기', validators=[django.core.validators.MaxValueValidator(25)])),
                ('user_id', models.ForeignKey(db_column='아이디', on_delete=django.db.models.deletion.CASCADE, to='polls.user_info')),
            ],
        ),
        migrations.CreateModel(
            name='Add_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mattress', models.PositiveIntegerField(db_column='매트리스', validators=[django.core.validators.MaxValueValidator(25)])),
                ('frige', models.PositiveIntegerField(db_column='냉장고', validators=[django.core.validators.MaxValueValidator(25)])),
                ('washer', models.PositiveIntegerField(db_column='세탁기', validators=[django.core.validators.MaxValueValidator(25)])),
                ('desk', models.PositiveIntegerField(db_column='책상', validators=[django.core.validators.MaxValueValidator(25)])),
                ('closet', models.PositiveIntegerField(db_column='옷장', validators=[django.core.validators.MaxValueValidator(25)])),
                ('cabinet', models.PositiveIntegerField(db_column='수납장', validators=[django.core.validators.MaxValueValidator(25)])),
                ('side_table', models.PositiveIntegerField(db_column='협탁', validators=[django.core.validators.MaxValueValidator(25)])),
                ('hanger', models.PositiveIntegerField(db_column='행거', validators=[django.core.validators.MaxValueValidator(25)])),
                ('user_id', models.ForeignKey(db_column='아이디', on_delete=django.db.models.deletion.CASCADE, to='polls.user_info')),
            ],
        ),
    ]
