# Generated by Django 3.2.2 on 2021-12-01 13:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', django_mysql.models.ListCharField(models.CharField(max_length=9), max_length=20, size=2)),
                ('rtype', models.CharField(db_column='type', default='square', max_length=10)),
                ('tagLoca', django_mysql.models.ListCharField(models.CharField(max_length=3), max_length=8, size=2)),
            ],
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_column='년')),
                ('month', models.IntegerField(db_column='월')),
                ('day', models.IntegerField(db_column='일')),
                ('gender', models.CharField(choices=[('여', '남'), ('남', '여')], db_column='성별', max_length=5)),
                ('job', models.CharField(choices=[('학생', '학생'), ('프리랜서', '프리랜서'), ('무직', '무직'), ('직장인', '직장인')], db_column='직업', max_length=20)),
                ('room_name', models.CharField(db_column='방이름', max_length=50, null=True)),
                ('room_size', models.IntegerField(db_column='방크기', null=True)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(db_column='rating')),
                ('tags', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.tags')),
            ],
        ),
        migrations.CreateModel(
            name='Fixed_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitchen', models.PositiveIntegerField(db_column='주방', validators=[django.core.validators.MaxValueValidator(25)])),
                ('fridge', models.PositiveIntegerField(db_column='냉장고', validators=[django.core.validators.MaxValueValidator(25)])),
                ('toilet', models.PositiveIntegerField(db_column='화장실', validators=[django.core.validators.MaxValueValidator(25)])),
                ('bed', models.PositiveIntegerField(db_column='침대', validators=[django.core.validators.MaxValueValidator(25)])),
                ('closet', models.PositiveIntegerField(db_column='옷장', validators=[django.core.validators.MaxValueValidator(25)])),
                ('washer', models.PositiveIntegerField(db_column='세탁기', validators=[django.core.validators.MaxValueValidator(25)])),
                ('front', models.PositiveIntegerField(db_column='현관', validators=[django.core.validators.MaxValueValidator(25)])),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Add_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mattress', models.PositiveIntegerField(db_column='매트리스', validators=[django.core.validators.MaxValueValidator(25)])),
                ('fridge', models.PositiveIntegerField(db_column='냉장고', validators=[django.core.validators.MaxValueValidator(25)])),
                ('washer', models.PositiveIntegerField(db_column='세탁기', validators=[django.core.validators.MaxValueValidator(25)])),
                ('desk', models.PositiveIntegerField(db_column='책상', validators=[django.core.validators.MaxValueValidator(25)])),
                ('closet', models.PositiveIntegerField(db_column='옷장', validators=[django.core.validators.MaxValueValidator(25)])),
                ('cabinet', models.PositiveIntegerField(db_column='수납장', validators=[django.core.validators.MaxValueValidator(25)])),
                ('side_table', models.PositiveIntegerField(db_column='협탁', validators=[django.core.validators.MaxValueValidator(25)])),
                ('hanger', models.PositiveIntegerField(db_column='행거', validators=[django.core.validators.MaxValueValidator(25)])),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
