from django.conf.urls import url
from . import views
from django.conf.urls.static import static
from django.conf import settings
urlpatterns =[
    url(r'^$',views.home,name='home'),
    url(r'^info1$',views.info1),
    url(r'^info2$',views.info2),
    url(r'^info3$',views.info3),
    url(r'^info4$',views.info4),
    url(r'signup',views.signup),
    url(r'logout', views.logout),
    url(r'login',views.login),
    url(r'recommend/',views.recommend),
    url(r'info1/info2',views.info2),
    url(r'info1/signup',views.signup),
    url(r'info1/info1',views.info1),
    url(r'info1/info2', views.info2),
    url(r'info1/info3', views.info3),
    url(r'info1/info4', views.info4),
    url(r'info1/home', views.home),
    url(r'info1/recommend', views.recommend),
    url(r'info2/info1', views.info1),
    url(r'info2/info3', views.info3),
    url(r'info2/info4', views.info4),
    url(r'info2/home', views.home),
    url(r'info2/recommend', views.recommend),
    url(r'info3/info1', views.info1),
    url(r'info3/info2', views.info2),
    url(r'info3/info4', views.info4),
    url(r'info3/home', views.info3),
    url(r'info3/recommend', views.recommend),
    url(r'info4/info1', views.info1),
    url(r'info4/info2', views.info2),
    url(r'info4/info3', views.info3),
    url(r'info4/home', views.home),
    url(r'info4/recommend', views.recommend),
    url(r'^login', views.login),
    url(r'home/login', views.login),
    url(r'info1/login', views.login),
    url(r'info2/login', views.login),
    url(r'info3/login', views.login),
    url(r'info4/login', views.login),
    url(r'info1/info2/login', views.login),
    url(r'info1/info3/login', views.login),
    url(r'info1/info4/login', views.login),
    url(r'info1/home/login', views.login),
    url(r'info2/info1/login', views.login),
    url(r'info2/info3/login', views.login),
    url(r'info2/info4/login', views.login),
    url(r'info2/home/login', views.login),
    url(r'info3/info1/login', views.login),
    url(r'info3/info2/login', views.login),
    url(r'info3/info4/login', views.login),
    url(r'info3/home/login', views.login),
    url(r'info4/info1/login', views.login),
    url(r'info4/info2/login', views.login),
    url(r'info4/info3/login', views.login),
    url(r'info4/home/login', views.login),
    url(r'info1/recommend', views.recommend),
    url(r'info2/recommend', views.recommend),
    url(r'info3/recommend', views.recommend),
    url(r'info4/recommend', views.recommend),
    url(r'info1/info2/recommend', views.recommend),
    url(r'info1/info3/recommend', views.recommend),
    url(r'info1/info4/recommend', views.recommend),
    url(r'info2/info1/recommend', views.recommend),
    url(r'info2/info3/recommend', views.recommend),
    url(r'info3/info4/recommend', views.recommend),
    url(r'info2/info1/recommend', views.recommend),
    url(r'info2/info3/recommend', views.recommend),
    url(r'info3/info4/recommend', views.recommend),



    url(r'recommend/logout',views.logout),
    url(r'info1/info2/logout',views.logout),
    url(r'info1/signup/logout',views.logout),
    url(r'info1/info1/logout',views.logout),
    url(r'info1/info2/logout', views.logout),
    url(r'info1/info3/logout', views.logout),
    url(r'info1/info4/logout', views.logout),
    url(r'info1/home/logout', views.logout),
    url(r'info1/recommend/logout', views.logout),
    url(r'info2/info1/logout', views.logout),
    url(r'info2/info3/logout', views.logout),
    url(r'info2/info4/logout', views.logout),
    url(r'info2/home/logout', views.logout),
    url(r'info2/recommend/logout', views.logout),
    url(r'info3/info1/logout', views.logout),
    url(r'info3/info2/logout', views.logout),
    url(r'info3/info4/logout', views.logout),
    url(r'info3/home/logout', views.logout),
    url(r'info3/recommend/logout', views.logout),
    url(r'info4/info1/logout', views.logout),
    url(r'info4/info2/logout', views.logout),
    url(r'info4/info3/logout', views.logout),
    url(r'info4/home/logout', views.logout),
    url(r'info4/recommend/logout', views.logout),
    url(r'^login/logout', views.logout),
    url(r'home/login/logout', views.logout),
    url(r'info1/login/logout', views.logout),
    url(r'info2/login/logout', views.logout),
    url(r'info3/login/logout', views.logout),
    url(r'info4/login/logout', views.logout),
    url(r'info1/info2/login/logout', views.logout),
    url(r'info1/info3/login/logout', views.logout),
    url(r'info1/info4/login/logout', views.logout),
    url(r'info1/home/login/logout', views.logout),
    url(r'info2/info1/login/logout', views.logout),
    url(r'info2/info3/login/logout', views.logout),
    url(r'info2/info4/login/logout', views.logout),
    url(r'info2/home/login/logout', views.logout),
    url(r'info3/info1/login/logout', views.logout),
    url(r'info3/info2/login/logout', views.logout),
    url(r'info3/info4/login/logout', views.logout),
    url(r'info3/home/login/logout', views.logout),
    url(r'info4/info1/login/logout', views.logout),
    url(r'info4/info2/login/logout', views.logout),
    url(r'info4/info3/login/logout', views.logout),
    url(r'info4/home/login/logout', views.logout),
    url(r'info1/recommend/logout', views.logout),
    url(r'info2/recommend/logout', views.logout),
    url(r'info3/recommend/logout', views.logout),
    url(r'info4/recommend/logout', views.logout),
    url(r'info1/info2/recommend/logout', views.logout),
    url(r'info1/info3/recommend/logout', views.logout),
    url(r'info1/info4/recommend/logout', views.logout),
    url(r'info2/info1/recommend/logout', views.logout),
    url(r'info2/info3/recommend/logout', views.logout),
    url(r'info3/info4/recommend/logout', views.logout),
    url(r'info2/info1/recommend/logout', views.logout),
    url(r'info2/info3/recommend/logout', views.logout),
    url(r'info3/info4/recommend/logout', views.logout),

]

urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)